- name: Set scripts executable
  run: |
   cd kernel # 或者您内核源代码的根目录
   chmod +x scripts/*.sh
   chmod +x scripts/clang-android.sh
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/minewhn/vivo_kernel_opensource_t1_5g
          kernel-dir: ksu
          kernel-branch: main
          config: vendor/holi-qgki_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          ksu: true
          ksu-version: main
          android-version: 12
          aosp-clang-version: r383902
          disable-lto: true
          anykernel3: true
