# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/minewhn/vivo_kernel_opensource_t1_5g/
          kernel-dir: ksu
          kernel-branch: main
          config: vendor/holi-qgki_defconfig
          arch: arm64
          aosp-gcc: false
          aosp-clang: true
          ksu: true
          ksu-version: main
          android-version: 13
          aosp-clang-version: r450784d
          disable-lto: true
          anykernel3: true
